### ISSUE TITLE
[Epic]: v2 implementation

### ISSUE THREAD

**Issue by kocubinski** [cosmos/iavl#851]
This issue tracks IAVL v2's SQLite backed implementation, including briefs of milestones hit (past), in progress work (present), overall strategy and near-term pending items (future).

main dev branch: https://github.com/cosmos/iavl/tree/v2-alpha6

## Benchmarks and Tests
Benchmarks demonstrating the performance of IAVL v2 are implemented.  To reproduce:

Generate the [OsmoLikeMany](https://github.com/cosmos/iavl/blob/a27f61e6651575577280362f1761447fec382e19/testutil/util.go#L185) dataset to disk, which approximates the state of osmosis's application.db in mid Sept 2023.

```
❯ mkdir -p /tmp/osmo-like-many/v1 && go run ./cmd gen emit --limit 1 --type osmo-like-many --out /tmp/osmo-like-many/v1
Nov  9 12:09:09 INF version=1 nodes=500,000
Nov  9 12:09:10 INF wrote 00-00000000.pb.gz module=streaming
...
last file written: /tmp/osmo-like-many/00-00000064.pb.gz

❯ mkdir -p /tmp/osmo-like-many/v2 && go run ./cmd gen emit --start 2 --limit 5000 --type osmo-like-many --out /tmp/osmo-like-many/v2
Nov  9 12:32:14 INF fast forward version=1 nodes=5,000,000
...
Nov  9 12:32:28 INF version=7 nodes=46,000,000
...
last file written: /tmp/osmo-like-many/v2/00-00000144.pb.gz
```

## General
- [x] Changelog storage (leaf set/delete)
- [x] Multitree PoC demonstrating concurrent `SaveVersion` and `LoadSnapshot`
  - Most users will probably use the existing logic in the store package, but this is useful for benchmarks.

## Latest Mode
Latest mode is the fastest and most memory intensive operating of mode of IAVL v2.  In this mode either the entire tree is stored in a memory, or all branch nodes (leaves excluded).

- [x] Leaf eviction filter
- [ ] No evictions (retain entire tree in memory)
- [x] Checkpoint sharding  
- [ ] Historical proofs from changelog replay

## Historical Mode
Historical mode approximates current behavior in IAVL v0 and v1 where all branch and leaf nodes are saved to disk at every version.  Primary use cases are nodes support historical proofs or full archive nodes.

## Snapshot

- [x] Pre-order snapshot
- [x] Pre-order restore
- [ ] Post-order snapshot
- [ ] Post-order restore

## Pruning
Discussions in the store v2 working group are split on the efficiency of both approaches below.  Orphan tracking is more time efficient and less space efficient, a tree diff is more space efficient but less time efficient.  Bench 

- [ ] Orphan tracking (IAVL v0 design)
- [ ] Tree diff (IAVL v1 design)
- [ ] Benchmarks of both approaches

## Osmosis integration
There is no better test than mainnet integration.  To support adoption and highlight any issues in IAVL v2 a PoC of integration into an osmosis node is in progress so that mainnet benchmarks may be obtained.  This will inform current and future development.

Osmosis forked Cosmos SDK with IAVL v2 patch: https://github.com/cosmos/cosmos-sdk/tree/kocubinski/osmosis-iavl-v2
Osmosis with the above patch: https://github.com/01builders/osmosis/tree/kocubinski/iavl-v2

**Comment by tac0turtle** [comment]
We talked on the team call about supporting import for preorder and post order to enable usage of iavlv2 in existing networks, but for new networks it would only be an export of preorder to simplify the code in the long run.
